### PR TITLE
Bump runtime version

### PR DESCRIPTION
**Pull request by rany2**

### CODE REVIEW

**Comment by skyjake** [comment]
Please see here for discussion why the 19.08 runtime is being used: https://github.com/skyjake/lagrange/issues/242

Summarizing, it’s because newer runtimes drop support for 32-bit Raspberry Pi.

Apart from extra disk space needed due to requiring both new and old runtimes being installed, I don’t see why the runtime here needs to be upgraded at this time. Could you elaborate on your rationale for upgrading?

**Comment by rany2** [comment]
No other rationale besides the fact that Lagrange is the only app that needs 19.08 and I'd like to cut down on extra disk space. 

Anyway support for 19.08 will be dropped sometime in 2021, so might as well switch now: https://wiki.gnome.org/GUADEC/2019/Hackingdays/FreedesktopSdk/Notes#line-56

**Comment by hfiguiere** [comment]
> Please see here for discussion why the 19.08 runtime is being used: [skyjake/lagrange#242](https://github.com/skyjake/lagrange/issues/242)
> 
> Summarizing, it’s because newer runtimes drop support for 32-bit Raspberry Pi.

64-bits Raspberry Pi OS works well.

**Comment by skyjake** [comment]
> support for 19.08 will be dropped sometime in 2021, so might as well switch now

I think that as long as 19.08 is still supported, there is no pressing need to move away from it or otherwise 32-bit Raspberry Pi users will be stuck with the old version of Lagrange.

> 64-bits Raspberry Pi OS works well.

Glad to hear! I'm considering installing it myself (running 32-bit currently), but judging by the [raspberrypi.org website](https://www.raspberrypi.org/software/operating-systems/#raspberry-pi-os-32-bit), they are still offering the 32-bit version as the default option. I'm assuming they'll eventually offer the 64-bit version as well for compatible devices.

**Pull request closed without merging**
